const TestCase = {
  DP1001: {
    id: 1,
    name: 'DP.1001',
    description: '检测CHM报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP1002: {
    id: 2,
    name: 'DP.1002',
    description: '检测CRM报文, 不能辨识BMS',
    param: 'AC0D', // 最高允许充电总电压: 350.0V
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP1003: {
    id: 3,
    name: 'DP.1003',
    description: '检测CRM报文, 能辨识BMS',
    param: '00010101AC0DAC0D31323334', // BMS通信协议版本号: V1.1, 电池类型: 铅酸电池, 整车动力蓄电池系统额定容量: 350.0Ah,
    // 整车动力蓄电池系统额定总电压: 350.0V, 电池生产厂商名称: 1234
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1001: {
    id: 4,
    name: 'DN.1001',
    description: 'BMS辨识异常, BMS停止发送',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1002: {
    id: 5,
    name: 'DN.1002',
    description: 'BMS辨识异常, 异常发送BRM',
    param: '00010101AC0DAC0D31323334',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1003: {
    id: 6,
    name: 'DN.1003',
    description: 'BMS辨识异常',
    param: 'AC0D', // 最高允许充电总电压: 350.0V
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1004: {
    id: 7,
    name: 'DN.1004',
    description: '无法进入充电配置阶段',
    param: '00010101AC0DAC0D31323334',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP2001: {
    id: 8,
    name: 'DP.2001',
    description: '检测CML报文',
    param: 'AC0DAC0DAC0DAC0D96F401AC0D', // 单体动力蓄电池最高允许充电电压: 35.00V, 最高允许充电电流: 50.0A, 动力蓄电池标称总能量: 350.0kW.h,
    // 最高允许充电总电压: 350.0V, 最高允许温度: 100°C, 整车动力蓄电池荷电状态: 50.0%, 整车动力蓄电池当前电池电压: 350.0V
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP2002: {
    id: 9,
    name: 'DP.2002',
    description: '发送BRO 0x00',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP2003: {
    id: 10,
    name: 'DP.2003',
    description: '发送BRO 0xAA',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2001: {
    id: 11,
    name: 'DN.2001',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2002: {
    id: 12,
    name: 'DN.2002',
    description: '停止发送BCP',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2003: {
    id: 13,
    name: 'DN.2003',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2004: {
    id: 14,
    name: 'DN.2004',
    description: '发送错误的BRO',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2005: {
    id: 15,
    name: 'DN.2005',
    description: '发送BRO != 0xAA',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2006: {
    id: 16,
    name: 'DN.2006',
    description: '发送BCP',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2007: {
    id: 17,
    name: 'DN.2007',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2008: {
    id: 18,
    name: 'DN.2008',
    description: '发送错误BRO',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2009: {
    id: 19,
    name: 'DN.2009',
    description: '发送BRO = 0x00',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2010: {
    id: 20,
    name: 'DN.2010',
    description: '发送BRO = 0xAA',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3001: {
    id: 21,
    name: 'DP.3001',
    description: '发送BCS BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3002: {
    id: 22,
    name: 'DP.3002',
    description: '发送BMV BMT BSP',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3003: {
    id: 23,
    name: 'DP.3003',
    description: '发送BSM',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3004: {
    id: 24,
    name: 'DP.3004',
    description: '发送BSM',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3005: {
    id: 25,
    name: 'DP.3005',
    description: '发送BSM',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3006: {
    id: 26,
    name: 'DP.3006',
    description: '发送BST',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3007: {
    id: 27,
    name: 'DP.3007',
    description: '停止充电',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3001: {
    id: 28,
    name: 'DN.3001',
    description: '停止发送BRO 发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3002: {
    id: 29,
    name: 'DN.3002',
    description: '停止发送BRO 发送BCS 不发送BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3003: {
    id: 30,
    name: 'DN.3003',
    description: '停止发送BRO 发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3004: {
    id: 31,
    name: 'DN.3004',
    description: '停止发送BRO 发送BCS 发送错误BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3005: {
    id: 32,
    name: 'DN.3005',
    description: '发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3006: {
    id: 33,
    name: 'DN.3006',
    description: '发送BCS 不发送BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3007: {
    id: 34,
    name: 'DN.3007',
    description: '发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3008: {
    id: 35,
    name: 'DN.3008',
    description: '发送BCS 发送错误BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3009: {
    id: 36,
    name: 'DN.3009',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3010: {
    id: 37,
    name: 'DN.3010',
    description: '发送错误BST',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP4001: {
    id: 38,
    name: 'DP.4001',
    description: '停止发送BST 发送BSD',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP4002: {
    id: 39,
    name: 'DP.4002',
    description: '重新开始充电',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4001: {
    id: 40,
    name: 'DN.4001',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4002: {
    id: 41,
    name: 'DN.4002',
    description: '发送错误BSD',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4003: {
    id: 42,
    name: 'DN.4003',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4004: {
    id: 43,
    name: 'DN.4004',
    description: '发送错误BSD',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
};

export default TestCase;
