const TestCase = {
  DP1001: {
    id: 11001,
    name: 'DP.1001',
    description: '检测CHM报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP1002: {
    id: 11002,
    name: 'DP.1002',
    description: '检测CRM报文, 不能辨识BMS',
    param: 'AC0D', // 最高允许充电总电压: 350.0V
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP1003: {
    id: 11003,
    name: 'DP.1003',
    description: '检测CRM报文, 能辨识BMS',
    param: '00010101AC0DAC0D31323334', // BMS通信协议版本号: V1.1, 电池类型: 铅酸电池, 整车动力蓄电池系统额定容量: 350.0Ah,
    // 整车动力蓄电池系统额定总电压: 350.0V, 电池生产厂商名称: 1234
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1001: {
    id: 1001,
    name: 'DN.1001',
    description: 'BMS辨识异常, BMS停止发送',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1002: {
    id: 1002,
    name: 'DN.1002',
    description: 'BMS辨识异常, 异常发送BRM',
    param: '00010101AC0DAC0D31323334',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1003: {
    id: 1003,
    name: 'DN.1003',
    description: 'BMS辨识异常',
    param: 'AC0D', // 最高允许充电总电压: 350.0V
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN1004: {
    id: 1004,
    name: 'DN.1004',
    description: '无法进入充电配置阶段',
    param: '00010101AC0DAC0D31323334',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP2001: {
    id: 12001,
    name: 'DP.2001',
    description: '检测CML报文',
    param: 'AC0DAC0DAC0DAC0D96F401AC0D', // 单体动力蓄电池最高允许充电电压: 35.00V, 最高允许充电电流: 50.0A, 动力蓄电池标称总能量: 350.0kW.h,
    // 最高允许充电总电压: 350.0V, 最高允许温度: 100°C, 整车动力蓄电池荷电状态: 50.0%, 整车动力蓄电池当前电池电压: 350.0V
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP2002: {
    id: 12002,
    name: 'DP.2002',
    description: '发送BRO 0x00',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP2003: {
    id: 12003,
    name: 'DP.2003',
    description: '发送BRO 0xAA',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2001: {
    id: 2001,
    name: 'DN.2001',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2002: {
    id: 2002,
    name: 'DN.2002',
    description: '停止发送BCP',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2003: {
    id: 2003,
    name: 'DN.2003',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2004: {
    id: 2004,
    name: 'DN.2004',
    description: '发送错误的BRO',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2005: {
    id: 2005,
    name: 'DN.2005',
    description: '发送BRO != 0xAA',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2006: {
    id: 2006,
    name: 'DN.2006',
    description: '发送BCP',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2007: {
    id: 2007,
    name: 'DN.2007',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2008: {
    id: 2008,
    name: 'DN.2008',
    description: '发送错误BRO',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2009: {
    id: 2009,
    name: 'DN.2009',
    description: '发送BRO = 0x00',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN2010: {
    id: 2010,
    name: 'DN.2010',
    description: '发送BRO = 0xAA',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3001: {
    id: 13001,
    name: 'DP.3001',
    description: '发送BCS BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3002: {
    id: 13002,
    name: 'DP.3002',
    description: '发送BMV BMT BSP',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3003: {
    id: 13003,
    name: 'DP.3003',
    description: '发送BSM',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3004: {
    id: 13004,
    name: 'DP.3004',
    description: '发送BSM',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3005: {
    id: 13005,
    name: 'DP.3005',
    description: '发送BSM',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3006: {
    id: 13006,
    name: 'DP.3006',
    description: '发送BST',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP3007: {
    id: 13007,
    name: 'DP.3007',
    description: '停止充电',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3001: {
    id: 3001,
    name: 'DN.3001',
    description: '停止发送BRO 发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3002: {
    id: 3002,
    name: 'DN.3002',
    description: '停止发送BRO 发送BCS 不发送BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3003: {
    id: 3003,
    name: 'DN.3003',
    description: '停止发送BRO 发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3004: {
    id: 3004,
    name: 'DN.3004',
    description: '停止发送BRO 发送BCS 发送错误BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3005: {
    id: 3005,
    name: 'DN.3005',
    description: '发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3006: {
    id: 3006,
    name: 'DN.3006',
    description: '发送BCS 不发送BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3007: {
    id: 3007,
    name: 'DN.3007',
    description: '发送BCL 不发送BCS',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3008: {
    id: 3008,
    name: 'DN.3008',
    description: '发送BCS 发送错误BCL',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3009: {
    id: 3009,
    name: 'DN.3009',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN3010: {
    id: 3010,
    name: 'DN.3010',
    description: '发送错误BST',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP4001: {
    id: 14001,
    name: 'DP.4001',
    description: '停止发送BST 发送BSD',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DP4002: {
    id: 14002,
    name: 'DP.4002',
    description: '重新开始充电',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4001: {
    id: 4001,
    name: 'DN.4001',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4002: {
    id: 4002,
    name: 'DN.4002',
    description: '发送错误BSD',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4003: {
    id: 4003,
    name: 'DN.4003',
    description: '停止发送报文',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
  DN4004: {
    id: 4004,
    name: 'DN.4004',
    description: '发送错误BSD',
    param: '',
    index: 0,
    status: '未开始',
    result: '',
    report: true,
  },
};

export default TestCase;
